FROM node:18-alpine

ARG SHOPIFY_API_KEY
ARG SHOPIFY_API_SECRET
ARG HOST
ARG SCOPES
ARG PORT
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ENV SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET
ENV HOST=$HOST
ENV SCOPES=$SCOPES
ENV PORT=$PORT
EXPOSE 8081
WORKDIR /app
COPY web .
RUN npm install
RUN cd frontend && npm install && npm run build
CMD ["npm", "run", "serve"]
