# fly.toml file generated for linkpro on 2022-10-27T17:57:38-05:00

app = "linkpro"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8081
  HOST = "https://linkpro.fly.dev"
  SHOPIFY_API_KEY = "0c0c550ed3f1008d7e62c6b2aff0e206"
  SCOPES = "read_products,write_products"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
