# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c0c550ed3f1008d7e62c6b2aff0e206"
name = "LinkPro"
handle = "link-pro"
application_url = "https://linkpro.fly.dev/"
embedded = true

[build]
dev_store_url = "matteos-new-store.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://linkpro.fly.dev/auth/callback",
  "https://linkpro.fly.dev/auth/shopify/callback",
  "https://linkpro.fly.dev/api/auth/callback",
  "https://up-hare-rightly.ngrok-free.app/",
  "https://up-hare-rightly.ngrok-free.app/auth/shopify/callback",
  "https://whispering-athens-t5bpsdy4vcxk.vapor-farm-g1.com/auth/shopify/callback",
  "https://link.pro/auth/shopify/callback",
  "https://staging.link.pro/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = true
